---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tbmaster-ac
  namespace: testbed-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testbed-system-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pods-viewer
subjects:
- kind: ServiceAccount
  name: tbmaster-ac
  namespace: testbed-system
---
apiVersion: v1
kind: Pod
metadata:
  name: tbmaster
  namespace: testbed-system
spec:
  serviceAccountName: "tbmaster-ac"
  containers:
  - name: tbmaster
    image: localhost:5000/tbmaster:v0.0.1
    imagePullPolicy: IfNotPresent
  nodeSelector:
    dedicated: master
    beta.kubernetes.io/arch: amd64
