---
apiVersion: v1
kind: Namespace
metadata:
  name: testbed-apps
  labels:
    name: testbed-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: testbed-system
  labels:
    name: testbed-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tbmaster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: testbed-apps
  name: testbed-apps-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: testbed-system
  name: testbed-system-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list","update","patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tbmaster-ac
  namespace: testbed-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testbed-node-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tbmaster-role
subjects:
- kind: ServiceAccount
  name: tbmaster-ac
  namespace: testbed-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testbed-system-pod-bind
  namespace: testbed-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testbed-system-manager
subjects:
- kind: ServiceAccount
  name: tbmaster-ac
  namespace: testbed-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testbed-apps-pod-bind
  namespace: testbed-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testbed-apps-manager
subjects:
- kind: ServiceAccount
  name: tbmaster-ac
  namespace: testbed-system
---
apiVersion: v1
kind: Pod
metadata:
  name: tbmaster
  namespace: testbed-system
  labels:
     app: tbmaster
spec:
  serviceAccountName: "tbmaster-ac"
  containers:
  - name: tbmaster
    image: localhost:5000/tbmaster:v0.0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 30776
  nodeSelector:
    dedicated: master
    beta.kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  namespace: testbed-system
  name: tbmaster-service
spec:
  selector:
    app: tbmaster
  type: NodePort
  ports:
    - protocol: TCP
      port: 30776
      targetPort: 30776
      nodePort: 30776
