apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: testbed-system
  name: acl-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acl-ac
  namespace: testbed-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acl-system-bind
  namespace: testbed-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acl-role
subjects:
- kind: ServiceAccount
  name: acl-ac
  namespace: testbed-system
---
apiVersion: v1
kind: Pod
metadata:
  name: acl
  namespace: testbed-system
  labels:
     app: acl
spec:
  serviceAccountName: "acl-ac"
  containers:
  - name: acl
    image: localhost:5000/acl:v0.0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
  nodeSelector:
    dedicated: master
    beta.kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  namespace: testbed-system
  name: acl-service
spec:
  selector:
    app: acl
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30777
