apiVersion: v1
kind: Pod
metadata:
  name: demo_image_detection
  namespace: demo
spec:
  hostNetwork: true
  containers:
  - name: detection
    image: 
    resources:
      limits:
        memory: "5000Mi"
        nvidia.com/gpu: 1
    command: ["python3"]
    args: ["/opt/main.py"]
