apiVersion: v1
kind: Pod
metadata:
  name: demo-image-detection
  namespace: demo
spec:
  hostNetwork: true
  restartPolicy: OnFailure
  containers:
  - name: detection
    image: 137.189.97.26:5000/batsnet_image_detect_demo
    resources:
      limits:
        memory: "4000Mi"
        nvidia.com/gpu: 1
